# Generated by Django 4.2.11 on 2024-11-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_squarecustomer_card_brand_squarecustomer_last_4_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercourseaccess",
            old_name="is_favorite",
            new_name="grace_period_enabled",
        ),
        migrations.RemoveField(
            model_name="usercourseaccess",
            name="course",
        ),
        migrations.RemoveField(
            model_name="usercourseaccess",
            name="is_saved",
        ),
        migrations.RemoveField(
            model_name="usercourseaccess",
            name="progress",
        ),
        migrations.RemoveField(
            model_name="usercourseaccess",
            name="renewal_date",
        ),
        migrations.RemoveField(
            model_name="usercourseaccess",
            name="renewal_task_id",
        ),
        migrations.AddField(
            model_name="usercourseaccess",
            name="has_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercourseaccess",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usercourseaccess",
            name="original_plan",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="usercourseaccess",
            name="selected_plan",
            field=models.CharField(
                choices=[
                    ("1-week", "1-week"),
                    ("4-week", "4-week"),
                    ("12-week", "12-week"),
                    ("lifetime", "lifetime"),
                ],
                default="1-week",
                max_length=20,
            ),
        ),
    ]
