# Generated by Django 4.2.11 on 2024-08-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_subcourse_remove_lesson_course_usersubcourseaccess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='parent_sub_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='myapp.subcourse'),
        ),
    ]
