# Generated by Django 4.2.11 on 2024-08-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_lesson_parent_sub_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('age_range', models.CharField(max_length=10)),
                ('main_goal', models.CharField(max_length=50)),
                ('income_source', models.CharField(max_length=50)),
                ('work_schedule', models.CharField(max_length=50)),
                ('job_challenges', models.TextField()),
                ('financial_situation', models.CharField(max_length=50)),
                ('annual_income_goal', models.CharField(max_length=50)),
                ('control_work_hours', models.CharField(max_length=10)),
                ('enjoy_routine_job', models.CharField(max_length=10)),
                ('time_saved_use', models.CharField(max_length=50)),
                ('job_interest_match', models.CharField(max_length=10)),
                ('digital_business_knowledge', models.CharField(max_length=50)),
                ('side_hustle_experience', models.CharField(max_length=50)),
                ('learning_new_skills', models.CharField(max_length=10)),
                ('ai_tools_familiarity', models.TextField()),
                ('content_writing_knowledge', models.CharField(max_length=50)),
                ('digital_marketing_knowledge', models.CharField(max_length=50)),
                ('ai_income_boost_awareness', models.CharField(max_length=50)),
                ('fields_interest', models.TextField()),
                ('ai_mastery_readiness', models.CharField(max_length=50)),
                ('focus_ability', models.CharField(max_length=50)),
                ('special_goal', models.CharField(max_length=50)),
                ('time_to_achieve_goal', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('receive_offers', models.BooleanField(default=False)),
            ],
        ),
    ]
