# Generated by Django 4.2.11 on 2025-02-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_aiusersubscription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aiusersubscription",
            old_name="is_active",
            new_name="is_auto_renew",
        ),
        migrations.AddField(
            model_name="aiusersubscription",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aiusersubscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("pro", "Pro Monthly"),
                    ("one-year", "One-Year Access"),
                ],
                default="free",
                max_length=50,
            ),
        ),
    ]
