# Generated by Django 4.2.11 on 2024-08-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_quizresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('receive_offers', models.BooleanField(default=False)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
