# Generated by Django 4.2.11 on 2024-08-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_emailcollection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailcollection',
            old_name='collected_at',
            new_name='created_at',
        ),
    ]
