# Generated by Django 4.2.11 on 2025-02-19 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0006_rename_is_active_aiusersubscription_is_auto_renew_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiusersubscription",
            name="chat_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aiusersubscription",
            name="chat_last_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aiusersubscription",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
