# Generated by Django 4.2.11 on 2024-08-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_collected_at_emailcollection_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseaccess',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
