# Generated by Django 4.2.11 on 2024-08-14 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_usercourseaccess_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcollection',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Delayed', 'Delayed')], default='Delayed', max_length=20),
        ),
        migrations.AddField(
            model_name='emailcollection',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
