# Generated by Django 4.2.11 on 2025-03-18 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0009_aichat_aimessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chathistory",
            name="date",
        ),
        migrations.RemoveField(
            model_name="chathistory",
            name="full_conversation",
        ),
        migrations.RemoveField(
            model_name="chathistory",
            name="summary",
        ),
        migrations.AddField(
            model_name="chathistory",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="chathistory",
            name="messages",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="chathistory",
            name="title",
            field=models.CharField(default="New Chat", max_length=255),
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="ai_bot",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
