# Generated by Django 4.2.11 on 2025-03-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_remove_chathistory_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chathistory",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
