# Generated by Django 4.2.11 on 2025-03-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_chathistory_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="chathistory",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
