# Generated by Django 4.2.11 on 2025-03-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_chathistory_last_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chathistory",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
