# Generated by Django 4.2.11 on 2025-03-20 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0013_alter_chathistory_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("specialty", models.TextField()),
                ("description", models.TextField()),
                (
                    "ai_type",
                    models.CharField(
                        choices=[
                            ("text", "Text-Based AI"),
                            ("image", "Image Generator AI"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("messages", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "ai_bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.aibot"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
