# Generated by Django 4.2.11 on 2024-08-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_knowledgebasecategory_knowledgebasesubcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
