# Generated by Django 4.2.11 on 2024-08-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_knowledgebasearticle_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcollection',
            name='first_login_completed',
            field=models.BooleanField(default=False),
        ),
    ]
