# Generated by Django 4.2.11 on 2025-03-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_aibot_aichatsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="aibot",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="aichatsession",
            name="session_status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="aichatsession",
            name="messages",
            field=models.JSONField(default=dict),
        ),
    ]
