# Generated by Django 4.2.11 on 2025-03-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_aibot_is_active_aichatsession_session_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aichatsession",
            name="manually_renamed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="aichatsession",
            name="messages",
            field=models.JSONField(default=list),
        ),
    ]
