# Generated by Django 4.2.11 on 2024-08-22 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0015_alter_emailcollection_first_login_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcollection',
            name='email',
        ),
        migrations.AlterField(
            model_name='emailcollection',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_collection', to=settings.AUTH_USER_MODEL),
        ),
    ]
