# Generated by Django 4.2.11 on 2025-03-20 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_aichatsession_manually_renamed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aibot",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="aibot",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="aibot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="aibot",
            name="description",
            field=models.TextField(help_text="Brief description of this AI."),
        ),
        migrations.AlterField(
            model_name="aibot",
            name="specialty",
            field=models.TextField(help_text="What this AI specializes in."),
        ),
    ]
