# Generated by Django 4.2.11 on 2025-03-26 20:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_aibot_created_at_aibot_slug_aibot_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aibot',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
