# Generated by Django 4.2.11 on 2024-08-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_emailcollection_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcollection',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
