# Generated by Django 4.2.11 on 2025-03-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_aibot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aibot',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief info of this AI.', null=True),
        ),
    ]
