# Generated by Django 4.2.11 on 2024-08-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_emailcollection_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresponse',
            name='age_range',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='control_work_hours',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='enjoy_routine_job',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='job_interest_match',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='learning_new_skills',
            field=models.CharField(max_length=50),
        ),
    ]
