# Generated by Django 5.1.2 on 2025-04-02 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_aibot_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aibot',
            name='cloned_from',
            field=models.ForeignKey(blank=True, help_text='If this bot was cloned, reference the original bot here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='myapp.aibot'),
        ),
        migrations.AddField(
            model_name='aibot',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If true, other users can see and clone this bot.'),
        ),
        migrations.AddField(
            model_name='aibot',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user who created this bot. Null for admin/system bots.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_bots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aibot',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
