# Generated by Django 4.2.11 on 2024-08-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_quizresponse_age_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcollection',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
