# Generated by Django 5.1.2 on 2025-04-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_aibot_cloned_from_aibot_is_public_aibot_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aibot',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
