# Generated by Django 4.2.11 on 2024-08-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_emailcollection_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresponse',
            name='user',
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=50),
        ),
    ]
