# Generated by Django 5.1.2 on 2025-04-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusersubscription',
            name='preferred_language',
            field=models.CharField(choices=[('en-US', 'English'), ('ja-JP', 'Japanese'), ('es-ES', 'Spanish'), ('fr-FR', 'French'), ('de-DE', 'German')], default='en-US', max_length=10),
        ),
    ]
