# Generated by Django 5.1.2 on 2025-04-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_aiusersubscription_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusersubscription',
            name='preferred_language',
            field=models.CharField(choices=[('en-US', 'English'), ('ja-JP', 'Japanese'), ('es-ES', 'Spanish'), ('fr-FR', 'French'), ('de-DE', 'German'), ('it-IT', 'Italian'), ('pt-PT', 'Portuguese (Portugal)'), ('pt-BR', 'Portuguese (Brazil)'), ('ru-RU', 'Russian'), ('zh-CN', 'Chinese (Simplified)'), ('zh-TW', 'Chinese (Traditional)'), ('ko-KR', 'Korean'), ('ar-SA', 'Arabic (Saudi Arabia)'), ('tr-TR', 'Turkish'), ('nl-NL', 'Dutch'), ('sv-SE', 'Swedish'), ('pl-PL', 'Polish'), ('da-DK', 'Danish'), ('no-NO', 'Norwegian'), ('fi-FI', 'Finnish'), ('he-IL', 'Hebrew'), ('th-TH', 'Thai'), ('hi-IN', 'Hindi'), ('cs-CZ', 'Czech'), ('ro-RO', 'Romanian'), ('hu-HU', 'Hungarian'), ('sk-SK', 'Slovak'), ('bg-BG', 'Bulgarian'), ('uk-UA', 'Ukrainian'), ('vi-VN', 'Vietnamese'), ('id-ID', 'Indonesian'), ('ms-MY', 'Malay'), ('sr-RS', 'Serbian'), ('hr-HR', 'Croatian'), ('el-GR', 'Greek'), ('lt-LT', 'Lithuanian'), ('lv-LV', 'Latvian'), ('et-EE', 'Estonian'), ('sl-SI', 'Slovenian'), ('is-IS', 'Icelandic'), ('sq-AL', 'Albanian'), ('mk-MK', 'Macedonian'), ('bs-BA', 'Bosnian'), ('ca-ES', 'Catalan'), ('gl-ES', 'Galician'), ('eu-ES', 'Basque'), ('hy-AM', 'Armenian'), ('fa-IR', 'Persian'), ('sw-KE', 'Swahili'), ('ta-IN', 'Tamil'), ('te-IN', 'Telugu'), ('kn-IN', 'Kannada'), ('ml-IN', 'Malayalam'), ('mr-IN', 'Marathi'), ('pa-IN', 'Punjabi'), ('gu-IN', 'Gujarati'), ('or-IN', 'Odia'), ('as-IN', 'Assamese'), ('ne-NP', 'Nepali'), ('si-LK', 'Sinhala')], default='en-US', max_length=10),
        ),
    ]
