# Generated by Django 4.2.11 on 2024-08-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_squarecustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseaccess',
            name='renewal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
