# Generated by Django 4.2.11 on 2025-05-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_aiusersubscription_preferred_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusersubscription',
            name='heard_about_us',
            field=models.CharField(choices=[('social_media', 'Social Media'), ('friend', 'Friend/Referral'), ('search', 'Search Engine'), ('event', 'Event/Expo'), ('other', 'Other')], default='other', max_length=50, verbose_name='How did you hear about us?'),
        ),
    ]
