# Generated by Django 4.2.11 on 2025-05-21 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_addon_document_userintegrationbot_useraddon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIIntegrationSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('base', 'Base'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('bot_limit', models.IntegerField()),
                ('doc_page_limit', models.IntegerField()),
                ('api_request_limit', models.IntegerField()),
                ('language_count', models.IntegerField()),
                ('team_member_limit', models.IntegerField()),
                ('behavior_training_limit', models.IntegerField()),
                ('white_label', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aiintegrationaccount',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.aiintegrationsubscriptionplan'),
        ),
    ]
