# Generated by Django 5.1.2 on 2025-06-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_quizquestion_quizchoice_userquizanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizFillerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz_fillers/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='quizchoice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_choices/'),
        ),
    ]
