# Generated by Django 5.1.2 on 2025-07-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_attendancelog_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='position_type',
            field=models.CharField(choices=[('regular', 'Regular Employee'), ('intern', 'Intern'), ('ojt', 'OJT'), ('freelancer', 'Freelancer')], max_length=20),
        ),
    ]
