# Generated by Django 4.2.11 on 2024-09-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_userprofile_avatar_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
