# Generated by Django 4.2.11 on 2024-09-06 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0036_alter_subscription_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('error', 'Error')], default='pending', max_length=10)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_logs', models.TextField(blank=True, null=True)),
                ('recurring', models.BooleanField(default=False)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
