# Generated by Django 4.2.11 on 2024-09-05 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_subscription_subscription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='end_date',
            new_name='expiration_date',
        ),
    ]
