# Generated by Django 5.1.2 on 2025-07-12 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_qrcode_file_alter_qrcode_image_alter_qrcode_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.qrcode')),
            ],
        ),
    ]
