# Generated by Django 5.1.2 on 2025-07-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_scanlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='action',
            field=models.CharField(choices=[('in', 'Time In'), ('out', 'Time Out')], max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='position_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
