# Generated by Django 4.2.11 on 2024-09-11 08:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_useranswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('paragraph', 'Paragraph'), ('image', 'Image'), ('header', 'Header'), ('task', 'Task'), ('question', 'Question'), ('multiple_questions', 'Multiple Questions'), ('multiple_choice', 'Multiple Choice')], max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('question', models.TextField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=200, null=True)),
                ('options', models.JSONField(blank=True, default=list, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='myapp.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
