# Generated by Django 4.2.11 on 2024-09-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_contentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseaccess',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercourseaccess',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
