# Generated by Django 4.2.11 on 2024-09-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_usercourseaccess_is_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseaccess',
            name='is_favorite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usercourseaccess',
            name='is_saved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
