# Generated by Django 4.2.11 on 2024-10-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_contentblock_video_url_alter_contentblock_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='type',
            field=models.CharField(choices=[('paragraph', 'Paragraph'), ('image', 'Image'), ('header', 'Header'), ('task', 'Task'), ('question', 'Question'), ('multiple_questions', 'Multiple Questions'), ('multiple_choice', 'Multiple Choice')], max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
