# Generated by Django 4.2.11 on 2024-10-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_remove_contentblock_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='type',
            field=models.CharField(choices=[('paragraph', 'Paragraph'), ('image', 'Image'), ('header', 'Header'), ('task', 'Task'), ('question', 'Question'), ('multiple_questions', 'Multiple Questions'), ('multiple_choice', 'Multiple Choice'), ('reflection', 'Reflection'), ('course_wrap_up', 'Course Wrap-Up'), ('congratulations', 'Congratulations'), ('video', 'Video')], max_length=50),
        ),
    ]
